

<div class="row" style="padding-top: 20px;">

  <div class="col-xs-12 col-md-6">
    <div class="form-inline">
      <div class="form-group">
        <input id="mk_search" class="form-control" type="text" name="mk_search" placeholder="Wprowadź frazę" />
      </div>
      <input type="submit" class="btn btn-default" name="mk_search_submit" id="mk_search_submit" value="Szukaj" />
      <img id="mk_loader" src="<?= $this->basePath() . '/img/loader.gif' ?>" width="20" height="20" alt="loader" style="display: none;" />
    </div>
  </div>
  <div class="col-xs-12 col-md-6">
    <div class="bs-callout bs-callout-warning">
        <h4>Wygenerowany plik:</h4>
        <div class="result">brak</div>
    </div>
  </div>

</div>
